




#! @Chapter Finitely presented categories generated by finite quivers

####################################
#
#! @Section GAP categories
#
####################################

#! @Description
#!  The &GAP; category of finitely presented categories.
DeclareCategory( "IsFpCategory",
        IsCapCategory );

#! @Description
#!  The &GAP; category of cells in a finitely presented category.
DeclareCategory( "IsCellInFpCategory",
        IsCapCategoryCell );

#! @Description
#!  The &GAP; category of objects in a finitely presented category.
DeclareCategory( "IsObjectInFpCategory",
        FilterIntersection(IsCapCategoryObject, IsCellInFpCategory ) );

#! @Description
#!  The &GAP; category of morphisms in a finitely presented category.
DeclareCategory( "IsMorphismInFpCategory",
        FilterIntersection( IsCapCategoryMorphism, IsCellInFpCategory ) );
